import 'package:json_annotation/json_annotation.dart';

part 'learning_path.g.dart';

/// An adaptive learning path for a child, generated by the recommendation engine.
@JsonSerializable(explicitToJson: true)
class LearningPath {
  final String pathId;
  final String childProfileId;
  final String ageGroup; // junior, mid, senior
  final String subject;
  final List<LearningPathNode> nodes;
  final String status; // active, completed, paused, abandoned
  final double overallProgress; // 0.0-1.0
  final DateTime createdAt;
  final DateTime? completedAt;
  final String schemaVersion;

  static const String currentSchemaVersion = '1.0.0';
  static const validStatuses = ['active', 'completed', 'paused', 'abandoned'];
  static const validAgeGroups = ['junior', 'mid', 'senior'];

  LearningPath({
    required this.pathId,
    required this.childProfileId,
    required this.ageGroup,
    required this.subject,
    this.nodes = const [],
    this.status = 'active',
    this.overallProgress = 0.0,
    DateTime? createdAt,
    this.completedAt,
    this.schemaVersion = currentSchemaVersion,
  }) : createdAt = createdAt ?? DateTime.now();

  factory LearningPath.fromJson(Map<String, dynamic> json) =>
      _$LearningPathFromJson(json);
  Map<String, dynamic> toJson() => _$LearningPathToJson(this);

  /// Current node the child should work on (first non-completed).
  LearningPathNode? get currentNode {
    for (final node in nodes) {
      if (node.status != 'completed') return node;
    }
    return nodes.isNotEmpty ? nodes.last : null;
  }

  /// Completed nodes count.
  int get completedNodes => nodes.where((n) => n.status == 'completed').length;

  /// Total estimated duration of remaining nodes in minutes.
  int get remainingDurationMinutes => nodes
      .where((n) => n.status != 'completed')
      .fold(0, (sum, n) => sum + n.estimatedDurationMinutes);

  List<String> validate() {
    final errors = <String>[];
    if (pathId.isEmpty) errors.add('pathId required');
    if (childProfileId.isEmpty) errors.add('childProfileId required');
    if (!validAgeGroups.contains(ageGroup)) {
      errors.add('Invalid ageGroup: $ageGroup');
    }
    if (!validStatuses.contains(status)) {
      errors.add('Invalid status: $status');
    }
    return errors;
  }
}

/// A single node in a learning path (lesson, assessment, game).
@JsonSerializable(explicitToJson: true)
class LearningPathNode {
  final String nodeId;
  final String nodeType; // lesson, game, assessment, review
  final String contentId;
  final String title;
  final int orderIndex;
  final List<String> prerequisiteNodeIds;
  final int estimatedDurationMinutes;
  final String difficulty;
  final String status; // locked, available, in_progress, completed, skipped
  final double progress; // 0.0-1.0
  final double? score;
  final int? attemptsCount;

  static const validNodeTypes = ['lesson', 'game', 'assessment', 'review'];
  static const validDifficulties = ['easy', 'medium', 'hard', 'adaptive'];
  static const validNodeStatuses = [
    'locked',
    'available',
    'in_progress',
    'completed',
    'skipped',
  ];

  LearningPathNode({
    required this.nodeId,
    required this.nodeType,
    required this.contentId,
    required this.title,
    required this.orderIndex,
    this.prerequisiteNodeIds = const [],
    this.estimatedDurationMinutes = 10,
    this.difficulty = 'adaptive',
    this.status = 'locked',
    this.progress = 0.0,
    this.score,
    this.attemptsCount,
  });

  factory LearningPathNode.fromJson(Map<String, dynamic> json) =>
      _$LearningPathNodeFromJson(json);
  Map<String, dynamic> toJson() => _$LearningPathNodeToJson(this);

  bool get isAvailable => status == 'available' || status == 'in_progress';
  bool get isCompleted => status == 'completed';

  List<String> validate() {
    final errors = <String>[];
    if (nodeId.isEmpty) errors.add('nodeId required');
    if (!validNodeTypes.contains(nodeType)) {
      errors.add('Invalid nodeType: $nodeType');
    }
    if (!validNodeStatuses.contains(status)) {
      errors.add('Invalid status: $status');
    }
    return errors;
  }
}
