/// Content lifecycle states for AI-generated content.
///
/// Per blueprint §18: Every AI output must follow the pipeline:
/// DRAFT_GENERATED → VALIDATION_FAILED / READY_FOR_REVIEW → HUMAN_APPROVED → PUBLISHED
library content_lifecycle;

/// Status of AI-generated content.
enum ContentLifecycleStatus {
  draftGenerated,
  validationFailed,
  readyForReview,
  humanApproved,
  rejected,
  published,
}

extension ContentLifecycleStatusExtension on ContentLifecycleStatus {
  String get value {
    switch (this) {
      case ContentLifecycleStatus.draftGenerated:
        return 'DRAFT_GENERATED';
      case ContentLifecycleStatus.validationFailed:
        return 'VALIDATION_FAILED';
      case ContentLifecycleStatus.readyForReview:
        return 'READY_FOR_REVIEW';
      case ContentLifecycleStatus.humanApproved:
        return 'HUMAN_APPROVED';
      case ContentLifecycleStatus.rejected:
        return 'REJECTED';
      case ContentLifecycleStatus.published:
        return 'PUBLISHED';
    }
  }

  static ContentLifecycleStatus fromString(String value) {
    switch (value) {
      case 'DRAFT_GENERATED':
        return ContentLifecycleStatus.draftGenerated;
      case 'VALIDATION_FAILED':
        return ContentLifecycleStatus.validationFailed;
      case 'READY_FOR_REVIEW':
        return ContentLifecycleStatus.readyForReview;
      case 'HUMAN_APPROVED':
        return ContentLifecycleStatus.humanApproved;
      case 'REJECTED':
        return ContentLifecycleStatus.rejected;
      case 'PUBLISHED':
        return ContentLifecycleStatus.published;
      default:
        return ContentLifecycleStatus.draftGenerated;
    }
  }

  bool get canPublish => this == ContentLifecycleStatus.humanApproved;
}

/// A draft content item generated by AI.
class ContentDraft {
  ContentDraft({
    required this.draftId,
    required this.skillId,
    required this.generatedAt,
    required this.lifecycleStatus,
    required this.generatedContent,
    required this.modelVersion,
    required this.promptVersion,
    required this.confidence,
    required this.childFacing,
    this.validationResult,
    this.humanReviewerId,
    this.humanReviewNote,
    this.rejectionReason,
  });

  final String draftId;
  final String skillId;
  final DateTime generatedAt;
  ContentLifecycleStatus lifecycleStatus;
  final String generatedContent;
  final String modelVersion;
  final String promptVersion;
  final double confidence;
  final bool childFacing;
  final String? validationResult;
  String? humanReviewerId;
  String? humanReviewNote;
  String? rejectionReason;

  bool advanceTo(ContentLifecycleStatus newStatus) {
    if (!isValidTransition(lifecycleStatus, newStatus)) return false;
    lifecycleStatus = newStatus;
    return true;
  }

  bool get needsHumanReview => childFacing;
  bool get canReachChild => lifecycleStatus == ContentLifecycleStatus.published;

  static bool isValidTransition(ContentLifecycleStatus from, ContentLifecycleStatus to) {
    final validTransitions = <ContentLifecycleStatus, List<ContentLifecycleStatus>>{
      ContentLifecycleStatus.draftGenerated: [
        ContentLifecycleStatus.validationFailed,
        ContentLifecycleStatus.readyForReview,
      ],
      ContentLifecycleStatus.validationFailed: [
        ContentLifecycleStatus.readyForReview,
      ],
      ContentLifecycleStatus.readyForReview: [
        ContentLifecycleStatus.humanApproved,
        ContentLifecycleStatus.rejected,
      ],
      ContentLifecycleStatus.humanApproved: [
        ContentLifecycleStatus.published,
      ],
      ContentLifecycleStatus.rejected: [],
      ContentLifecycleStatus.published: [],
    };
    return validTransitions[from]?.contains(to) ?? false;
  }
}
